// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClq0I5AlAWPQ6ofmJbLz010HYNSg_PzMo',
    appId: '1:1054694345677:web:7a17215e85e7493e6ad284',
    messagingSenderId: '1054694345677',
    projectId: 'flutter-chat2-d357b',
    authDomain: 'flutter-chat2-d357b.firebaseapp.com',
    storageBucket: 'flutter-chat2-d357b.appspot.com',
    measurementId: 'G-WQSRCKESNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEmgEwID9O5MXHzC8VWCuXHU0XzfCjxvE',
    appId: '1:1054694345677:android:c6506b65cedd7d0d6ad284',
    messagingSenderId: '1054694345677',
    projectId: 'flutter-chat2-d357b',
    storageBucket: 'flutter-chat2-d357b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvgk_bF5xT2LSODaPmbGudKfOfkPvppWg',
    appId: '1:1054694345677:ios:68c1eae8b8081c3a6ad284',
    messagingSenderId: '1054694345677',
    projectId: 'flutter-chat2-d357b',
    storageBucket: 'flutter-chat2-d357b.appspot.com',
    iosClientId: '1054694345677-mv2hv0uu693cscrdi20q21t2t3qq9v7l.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvgk_bF5xT2LSODaPmbGudKfOfkPvppWg',
    appId: '1:1054694345677:ios:68c1eae8b8081c3a6ad284',
    messagingSenderId: '1054694345677',
    projectId: 'flutter-chat2-d357b',
    storageBucket: 'flutter-chat2-d357b.appspot.com',
    iosClientId: '1054694345677-mv2hv0uu693cscrdi20q21t2t3qq9v7l.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
